### ISSUE TITLE
Add update orders service API v3

### ISSUE THREAD

**Issue by kroniak** [kroniak/extensions-ecwid#23]
#13

**Comment by Arachnid** [comment]
Any timeline on this? I need this for my project, and I'd happily take it on if you don't have time.

**Comment by kroniak** [comment]
@Arachnid No, I don't have time now. I think that I can do this for 2 weeks. You can add an Interface, code and tests to dev brunch and make PR.

**Comment by Arachnid** [comment]
Any thoughts on what you'd like the interface to look like?

**Comment by kroniak** [comment]
@Arachnid Look

Base Interface for OrderClient
https://github.com/kroniak/extensions-ecwid/blob/dev/src/Ecwid/Services/Interfaces.cs#L146
Not need to modify.

File to implementation https://github.com/kroniak/extensions-ecwid/blob/dev/src/Ecwid/Services/EcwidClientOrders.cs
For intenal logic for update method.

How to this was implemented in Legacy client 
https://github.com/kroniak/extensions-ecwid/blob/dev/src/Ecwid/Services/Legacy/EcwidLegacyClientOrders.cs#L202

The best way is implementation a QueryBuilderExtension with arguments with new OrderFields and internal method to update order self.

Look to https://github.com/kroniak/extensions-ecwid/blob/dev/src/Ecwid/Services/QueryBuilder/LegacyOrdersQueryBuilderExtensions.cs#L336

**Comment by Arachnid** [comment]
The new orders API lacks bulk update functionality; given that, I wonder if it would make more sense to put an Update method on the Order object, or on the client, instead?

**Comment by kroniak** [comment]
@Arachnid best way isto put an update method to both object client and order.
I will look your PR, on this week. Need to write some tests.

**Comment by kroniak** [comment]
https://github.com/kroniak/extensions-ecwid/commit/a2bca4510327344c26553a7068625ebf773e3b28

https://github.com/kroniak/extensions-ecwid/commit/af5fd6a289505cbc8092710f1fe61261183050cc
