### ISSUE TITLE
New ecwid tokens not accepted

### ISSUE THREAD

**Issue by Arachnid** [kroniak/extensions-ecwid#34]
Ecwid now issues tokens of the form "secret_xxx", which the library rejects as invalid. The regex needs updating or (preferably) removing, since there's no saying what ecwid tokens will look like in the future.

In the meantime, here's a nasty workaround for anyone else experiencing this issue:

            var credentials = new EcwidCredentials(Properties.Ecwid.Default.StoreId, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
            typeof(EcwidCredentials).GetField("_token", System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance).SetValue(credentials, Properties.Ecwid.Default.AccessToken);
            client = new EcwidClient(credentials);

**Comment by kroniak** [comment]
@Arachnid Please give me a new token format.

**Comment by Arachnid** [comment]
I believe there's also public tokens now, though I don't know what they start with. I'd highly recommend just removing the validation, since Ecwid may change their token formats arbitrarily and without notice.

**Comment by kroniak** [comment]
@Arachnid I made changes. Look at commits.

**Comment by Arachnid** [comment]
Ah, fantastic, thank you. Will you push out a new release?

**Comment by kroniak** [comment]
@Arachnid  Yes, I will push out new package asap.

**Comment by kroniak** [comment]
@Arachnid please check

**Comment by Arachnid** [comment]
Nuget doesn't show a new version as available.

**Comment by kroniak** [comment]
@Arachnid wait, wait
