### ISSUE TITLE
Discount Coupons API

### ISSUE THREAD

**Issue by lxalln** [kroniak/extensions-ecwid#39]
It looks like the [Discount Coupons API](https://developers.ecwid.com/api-documentation/discount-coupons) is not yet implemented.

Is there any reason why I shouldn't have a crack at it and submit a PR?

I assume following the existing pattern of code should be fine. Creating a partial class `EcwidClientDiscountCoupons`.

From what I can see I won't be able to implement the 'real' tests, as the mocky api will need to be set up.

**Comment by kroniak** [comment]
You are fully free to submit this PR.

Look at interfaces. partial class is good idea.
You can use testhttp class from Flurl to make test env.

**Comment by kroniak** [comment]
And please use a dev branch to PR.
