### ISSUE TITLE
GPL License

### ISSUE THREAD

**Issue by lxalln** [kroniak/extensions-ecwid#40]
Is there a particular reason that GPL v3 is being used for this project?

I would imagine most products that will interact with the ecwid API are going to be proprietary software and are thus excluded from referencing this library.

Would you consider lowering the licensing requirements (perhaps the Apache license)? Or perhaps dual licensing?

**Comment by kroniak** [comment]
Hello. Thank you for your q. I think I will can drop to Mit.
What do you think?

**Comment by lxalln** [comment]
MIT would work. That license still requires that users attribute where the code came from.

This change would save me a lot of time writing a full ecwid client!

**Comment by kroniak** [comment]
#41
