### ISSUE TITLE
Add Pickup Time

### ISSUE THREAD

**Issue by Tunertron** [kroniak/extensions-ecwid#52]
I just tagged this onto OrderEntry.cs:

```
        /// <summary>
        /// Gets or sets order pickup time, e.g 2014-06-06 18:57:19 +0000.
        /// </summary>
        /// <value>
        /// The pickup time.
        /// </value>
        [JsonProperty("pickupTime")]
        public DateTime PickupTime { get; set; }
```
I notice that the notification emails will use this time nicely. E.g. set to "PROCESSING" add a Pickup Time then update the order :)

**Comment by kroniak** [comment]
I am not support this repo at this time. You can add PR
